### ISSUE TITLE
latest xk6-sql version forces to use latest k6 version making it incompatible with other modules

### ISSUE THREAD

**Issue by fabiosilva85** [grafana/xk6-sql#20]
This latest version of xk6-sql forces to use k6 version 0.38, making this incompatible with other xk6 plugins (https://github.com/szkiba/xk6-dotenv). Even when i execute the build forcing to be on v0.36, always got to latest k6 version build because of this plugin.

**Comment by imiric** [comment]
Hi there!

The upgrade to k6 v0.38.0 was done to fix a breaking change in the extension API introduced in the latest k6 version, otherwise this extension would stop working. Since xk6 (or Go, actually) will build with the latest k6 version specified by extensions, this makes any upgraded extension incompatible with extensions that haven't been fixed. We can't go back at this point in this project, so the only solution is to ask the xk6-dotenv author to upgrade their extension to v0.38.0, as I see [you've already done](https://github.com/szkiba/xk6-dotenv/issues/5).
