### ISSUE TITLE
Request to accept the username and password as two different arguments for db.open function.

### ISSUE THREAD

**Issue by vamsidarbhamulla** [grafana/xk6-sql#33]
Hi, 

I'm trying to connect to aws rds based postgres instance with a password string containing a good number of special characters. 

I did observe an error as  **net/url: invalid userinfo**  while building the xk6-sql extension and providing the connection string.

After a bit of research I'm able to fix my issue with a local build of xk6-sql by following the below two suggestions:

- https://github.com/golang/go/issues/23392
- https://stackoverflow.com/a/64818762

I'm pretty new to golang ecosystem so requesting to get the same code changes on the actual repo if it makes sense.

```golang
// need to add two more arguments for username and password
func (*SQL) Open(database string, connectionString string, username string, password string) (*dbsql.DB, error) {
	supportedDatabases := []string{"mysql", "postgres", "sqlite3", "sqlserver"}
	if !contains(supportedDatabases, database) {
		return nil, fmt.Errorf("database %s is not supported", database)
	}

   // modified code suggestion start
    connectionUrl, connErr := url.Parse(connectionString)
    if connErr != nil {
         fmt.Errorf("ERROR: %v\n", connErr)
         return nil, connErr
    }
    connectionUrl.User = url.UserPassword(username, password)

	db, err := dbsql.Open(database, connectionUrl.String())
	// modified code suggestion end 
	if err != nil {
		return nil, err
	}

	return db, nil
}
```

**Comment by imiric** [comment]
Hi there!

If you're using special characters in your connection string, you need to URL encode them first.

You can use the builtin `encodeURIComponent()` function for this. For example:

```javascript
const pass = encodeURIComponent('pass[@#$%^&]');
const db = sql.open('postgres', `postgres://user:${pass}@127.0.0.1:5432/postgres?sslmode=disable`);
```

I confirmed this works on a local Postgres instance, so it should work with AWS RDS as well.

So we don't need to add separate arguments for this, even though it wouldn't be a breaking change.

**Comment by vamsidarbhamulla** [comment]
Hi, 

Thanks for the quick response. Unfortunately, I could not make it work either with `encodeURIComponent() ` or even by providing an already encoded password directly. 

The only observed difference so far I can see is that `encodeURIComponent` function did not encode these two characters  `!)` but even after replacing them with the actual encoded values it did not work for me. 

I would prefer to use my local build with username and password as different arguments on the `open` function in the golang `sql.go` script as that is the only approach I can make it work. 

Thanks again for your feedback. I really appreciate it.

**Comment by imiric** [comment]
@vamsidarbhamulla Sorry to read that, but I think there's another reason you're getting the `invalid userinfo`. You're right that the `!)` characters don't get encoded, but from my tests with a local Postgres instance, they don't need to be. I can connect fine by either encoding them or not.

Can you test with plain Postgres and not RDS, to confirm if it's an RDS issue? I run a Docker container with:
```
docker run --rm --name postgres -p 127.0.0.1:5432:5432 -e POSTGRES_USER=user -e POSTGRES_PASSWORD='pass[@#$%^&!)]' postgres:14.4
```

The reason I'm reluctant to do this change is because `db.open` is not just used for Postgres. While technically JavaScript allows calling functions with less arguments than defined, and it likely wouldn't be breaking change for k6 scripts, we would need to ensure it works well for other RDBMSs, and it's not such a trivial change.

You could just keep using your fork, but I don't see a reason why `encodeURIComponent()` shouldn't work in this case.

**Comment by vamsidarbhamulla** [comment]
Hi @imiric - I did test it with plain postgres docker setup and I'm able to interact with the local docker DB. Not sure what exactly is the issue with RDS setup and the` inavlid userinfo` error. 

I totally agree with the reasoning behind not modifying the current code changes. I will keep using the fork. Thanks for the response.
